# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'position_design.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_1(object):
    def setupUi(self, Dialog_1):
        Dialog_1.setObjectName("Dialog_1")
        Dialog_1.resize(600, 500)
        self.formLayoutWidget = QtWidgets.QWidget(Dialog_1)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 10, 550, 350))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_3.setContentsMargins(10, 10, 10, 10)
        self.formLayout_3.setSpacing(15)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_27 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.label_28 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.label_29 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.label_30 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.pushButton_8 = QtWidgets.QPushButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.pushButton_8)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_10)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_11)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_12.setFont(font)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_12)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_13.setFont(font)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_13)
        self.label_32 = QtWidgets.QLabel(Dialog_1)
        self.label_32.setGeometry(QtCore.QRect(20, 270, 550, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(Dialog_1)
        self.label_33.setGeometry(QtCore.QRect(30, 320, 220, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.lineEdit_14 = QtWidgets.QLineEdit(Dialog_1)
        self.lineEdit_14.setGeometry(QtCore.QRect(300, 320, 260, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_14.setFont(font)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.pushButton_9 = QtWidgets.QPushButton(Dialog_1)
        self.pushButton_9.setGeometry(QtCore.QRect(30, 380, 120, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_34 = QtWidgets.QLabel(Dialog_1)
        self.label_34.setGeometry(QtCore.QRect(20, 420, 550, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(Dialog_1)
        self.label_35.setGeometry(QtCore.QRect(30, 450, 550, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")

        self.retranslateUi(Dialog_1)
        QtCore.QMetaObject.connectSlotsByName(Dialog_1)

    def retranslateUi(self, Dialog_1):
        _translate = QtCore.QCoreApplication.translate
        Dialog_1.setWindowTitle(_translate("Dialog_1", "Добавить должность"))
        self.label_27.setText(_translate("Dialog_1", "Должность"))
        self.label_28.setText(_translate("Dialog_1", "Коэф. Зн."))
        self.label_29.setText(_translate("Dialog_1", "Зарплата по рынку"))
        self.label_30.setText(_translate("Dialog_1", "Доп. инфо"))
        self.pushButton_8.setText(_translate("Dialog_1", "Добавить"))
        self.label_32.setText(_translate("Dialog_1", "_____________________________________________________________"))
        self.label_33.setText(_translate("Dialog_1", "Введите должность:"))
        self.pushButton_9.setText(_translate("Dialog_1", "Удалить"))
        self.label_34.setText(_translate("Dialog_1", "_____________________________________________________________"))
        self.label_35.setText(_translate("Dialog_1", "Результат:"))
